### ISSUE TITLE
Corner case

### ISSUE THREAD

**Issue by sergiocorreia** [matthieugomez/stata-regife#1]
When running this on the corner case of a factor being equal to "_n", it fails with a confusing/unrelated message.

EG:

``` stata
sysuse auto
gen i = _n
regife price weight, f(i turn, 1)
```

Quite low priority, but still.

Thanks!
Sergio

**Comment by matthieugomez** [comment]
Thanks. I committed a version that catches this error. Do you know a way to get the error message returned by reghdfe, not just the return code?

**Comment by sergiocorreia** [comment]
AFAIK there is no built-in way of doing that in Stata.

I'm guessing you want to catch an error (capture) and re-raise it, like in most modern languages, but I'm not aware of a way. Since almost all of my error messages go to an internal Assert.ado script, I thought about saving the messages in a global "RC_MESSAGE" so I may be able to do that.

**Comment by matthieugomez** [comment]
yes exactly. I guess I'll end up catching the error, print "reghdfe fails because" and retry reghdfe so that the relevant error message is printed. This code is already a mess anyway.
