### ISSUE TITLE
Weighted estimation

### ISSUE THREAD

**Issue by marcossn79** [matthieugomez/stata-regife#4]
Dear Matthieu,

I am trying to carry out a weighted regression (by municipality size):

regife growth attack_1_2-attack_13_14 [w=popul], a(i.id i.year) f(id year, 1)

However, I obtain the following error message:

(analytic weights assumed)
if not allowed
r(101);

Although, following the help file, I have tried using constant weights by municipality this does not work either.

Thank you very much for your help!

Marcos

**Comment by matthieugomez** [comment]
Thanks for the report. The bug should be corrected in the version available here.
Look at the instructions in the README to install the latest version on Github

**Comment by marcossn79** [comment]
Thank you very much. This version works properly in Stata 12.
